name: 'Stale issues Bot'

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
    
    steps:
      - uses: actions/stale@v6
        with:
          repo-token: "${{ secrets.BOT_TOKEN }}"
          exempt-issue-labels: 'do-not-stale,enhancement'
          stale-issue-message: 'This issue has been automatically marked as stale because it has been without activity for 90 days. This issue will be closed in 14 days unless you comment or remove the stale label.'
          close-issue-message: 'This issue was closed because it was stale for 14 days without any activity.'
          days-before-issue-stale: 90
          days-before-issue-close: 14
          days-before-pr-close: -1
          days-before-pr-stale: -1
          operations-per-run: 300
